name: Deploy Linux VM with Bicep

# Trigger the workflow on push
on: 
  push:

# Global environment variables
env:
  AZURE_RESOURCE_GROUP: 'minecraftRG'
  AZURE_LOCATION: 'eastus2'
  VM_NAME: 'minecraft-linux'

# Permissions needed for Azure authentication
permissions:
  id-token: write
  contents: read

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Azure CLI and Bicep
      - name: Install Azure CLI and Bicep
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az bicep install

      # Run Bicep linter
      - name: Lint Bicep Files
        run: az bicep build --file ./infra/main.bicep

     # Deploy Bicep template
     - name: Deploy Bicep Template
     run: |
       az deployment group create \
         --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
         --template-file ./infra/main.bicep \
         --parameters \
           vmName=${{ env.VM_NAME }} \
           adminPassword="${{ secrets.VM_ADMIN_PASSWORD }}"

      # Optional: Add a step to verify VM deployment
      - name: Verify VM Deployment
        run: |
          az vm list \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --query "[?name=='${{ env.VM_NAME }}']"