name: Deploy Linux VM with Bicep

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-vm:
    name: Deploy Linux VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy compute.bicep to Minecraft RG
        run: |
          az deployment group create \
            --name linuxVmDeployment \
            --resource-group "Minecraft RG" \
            --template-file infrastructure/compute.bicep \
            --parameters @infrastructure/compute.parameters.json \
            --subscription 3d36185b-63ee-4012-b04c-98a78f4bf5d7
