name: Deploy compute.bicep to Azure

on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      OUTPUT_PATH: ${{ github.workspace }}

    steps:
      # 1) Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Log into Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3) Deploy Bicep file
      - name: Deploy bicep
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: 3d36185b-63ee-4012-b04c-98a78f4bf5d7
          resourceGroupName: MinecraftRG
          template: ./infrastructure/compute.bicep
          parameters: |
            # If your Bicep expects parameters, 
            # pass them in the format:
            # paramName1=paramValue1
            # paramName2=paramValue2
          # Optional inputs you can add if needed:
          # deploymentName: DeployCompute
          # deploymentScope: resourceGroup
          # deploymentMode: Incremental
