name: Deploy Linux VM with Bicep

# Trigger the workflow on push
on: 
  push:

# Global environment variables
env:
  AZURE_RESOURCE_GROUP: 'minecraftRG'
  AZURE_LOCATION: 'eastus2'
  VM_NAME: 'minecraft-linux'

# Permissions needed for Azure authentication
permissions:
  id-token: write
  contents: read

jobs:
  lint:
    name: Lint Bicep Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Bicep linter
        run: az bicep build --file deploy/main.bicep

  validate-and-deploy:
    name: Validate and Deploy Bicep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep Template
        uses: azure/cli@v1
        with:
          inlineScript: |
            az deployment group create \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --template-file infrastructure/compute.bicep \
              --parameters adminPasswordOrKey='${{ secrets.ADMIN_PASSWORD }}'
