name: Deploy Linux VM with Bicep

# Trigger the workflow on push
on: 
  push:

# Global environment variables
env:
  AZURE_RESOURCE_GROUP: 'minecraftRG'
  AZURE_LOCATION: 'eastus2'
  VM_NAME: 'minecraft-linux'

# Permissions needed for Azure authentication
permissions:
  id-token: write
  contents: read

jobs:
  lint:
    name: Lint Bicep Templates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Bicep Linter
        uses: synergy-au/bicep-lint-action@v1
        with:
          analyse-all-files: "true"
          bicep-version: "latest"

  deploy:
    name: Deploy Bicep Template
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep Template
        run: |
          az deployment group create \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --template-file ./infra/main.bicep \
            --parameters \
              vmName=${{ env.VM_NAME }} \
              adminPassword="${{ secrets.VM_ADMIN_PASSWORD }}"

      - name: Verify VM Deployment
        run: |
          az vm list \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --query "[?name=='${{ env.VM_NAME }}']"
